info:
  component: Hystrix Dashboard
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 7979

management:
  context-path: /manage
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /manage/info
    healthCheckUrlPath: /manage/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/