info:
  component: Turbine

turbine:
  clusterNameExpression: new String('default')
  appConfig: zuul,sample-service

server:
  port: 8989

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/