server:
  port: ${PORT:12234}
  
endpoints.jmx.enabled: false
spring.jmx.enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:     
    hostname: localhost
    nonSecurePort: 8080
    statusPageUrlPath: /OpenAM-12.0.0/isAlive.jsp
    healthCheckUrlPath: /OpenAM-12.0.0/isAlive.jsp
    metadataMap:
      instanceId: openam1