management.security.enabled: true
security.basic.enabled: false
info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    api: 
      path: /api/**
      serviceId: sample-service
      stripPrefix: false
    ui:
      path: /ui/**
      serviceId: frontend
    test:
      path: /testopenam/**
      serviceId: testopenam
      stripPrefix: true
    test2:
      path: /test2/**
      url: http://localhost:8765/test
      stripPrefix: true
      

server:
  port: 8765
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/